# Generated by Django 5.2.17 on 2026-08-21 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('blog', 'Blog'), ('linkedin', 'LinkedIn Post'), ('youtube', 'YouTube Script'), ('instagram', 'Instagram Caption'), ('twitter', 'Twitter/X Thread'), ('newsletter', 'Newsletter'), ('email', 'Email'), ('rewrite', 'Rewrite'), ('summarize', 'Summarize'), ('expand', 'Expand'), ('humanize', 'Humanize'), ('seo_title', 'SEO Title'), ('meta_description', 'Meta Description')], max_length=50)),
                ('topic', models.TextField()),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('input_content', models.TextField(blank=True)),
                ('output_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='creator.project')),
            ],
        ),
    ]
